# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js WEBSITE

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 22.20.0 ]

   
    steps:
    - uses: actions/checkout@v4
      with:
       clean: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Create .env file
      run: |
        echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
        echo "EMAIL_APP_PASSWORD=${{ secrets.EMAIL_APP_PASSWORD }}" >> .env
        echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
        echo "NEXT_PUBLIC_API_BLOG=${{ secrets.NEXT_PUBLIC_API_BLOG }}" >> .env
        echo "NEXT_PUBLIC_API_ASSISTANT=${{ secrets.NEXT_PUBLIC_API_ASSISTANT }}" >> .env
    
